### ISSUE TITLE
Implement IWantToRunWhenEndpointStarts

### ISSUE THREAD

**Issue by kbaley** [Particular/NServiceBus.Host#60] opened 2016-03-16 21:14 UTC
Connects to https://github.com/Particular/NServiceBus/issues/3342

With `IWantToRunWhenBusStartsAndStops` becoming obsolete, each host will need to implement this functionality (including tests).

**Comment by andreasohlund** [comment] 2016-03-23 12:19
@kbaley how about we close this one as a duplicate of Particular/NServiceBus#3342 since that one is tracking this? (cc @colin-higgins )

**Closed** 2016-03-23 18:08 UTC
Labels: Project: V6 Launch
