### ISSUE TITLE
Unhandled exceptions from other threads should be logged

### ISSUE THREAD

**Issue by rosieks** [Particular/NServiceBus.Host#36] opened 2015-03-06 08:26 UTC
While running NServiceBus.Host.exe version 4.2 I received the following entry in the event log:

    Application: NServiceBus.Host.exe
    Framework Version: v4.0.30319
    Description: The process was terminated due to an unhandled exception.
    Exception Info: NHibernate.ADOException
    Stack:
       at NHibernate.Connection.ConnectionProvider.CloseConnection(System.Data.IDbConnection)
       at NHibernate.Connection.DriverConnectionProvider.CloseConnection(System.Data.IDbConnection)
       at NHibernate.AdoNet.ConnectionManager.CloseConnection()
       at NHibernate.AdoNet.ConnectionManager.AfterTransaction()
       at NHibernate.Impl.SessionImpl.AfterTransactionCompletion(Boolean, NHibernate.ITransaction)
       at NHibernate.Transaction.AdoNetWithDistributedTransactionFactory+DistributedTransactionContext.System.Transactions.IEnlistmentNotification.Rollback(System.Transactions.Enlistment)
       at System.Transactions.Oletx.OletxVolatileEnlistment.Rollback()
       at System.Transactions.Oletx.OletxPhase0VolatileEnlistmentContainer.Aborted()
       at System.Transactions.Oletx.OutcomeEnlistment.InvokeOutcomeFunction(System.Transactions.TransactionStatus)
       at System.Transactions.Oletx.OletxTransactionManager.ShimNotificationCallback(System.Object, Boolean)
       at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(System.Object, Boolean)

Unfortunately this exception wasn't logged in host log so I don't know what was the message in exception. For now I have added the following code to log all unhandled exceptions - it would be nice if something similar was added to host:

    public static Configure LogAppDomainUnhandledException(this Configure config)
    {
        AppDomain.CurrentDomain.UnhandledException += ConfigurationExtensions.OnUnhandledException;

        return config;
    }

    private static void OnUnhandledException(object sender, UnhandledExceptionEventArgs e)
    {
        LogManager.GetLogger(typeof(AppDomain)).Fatal("Unhandled exception", e.ExceptionObject as Exception);
    }

**Comment by johnsimons** [comment] 2015-03-09 00:54
@rosieks what versions are you using?

**Comment by rosieks** [comment] 2015-03-09 09:16
I'm using NServiceBus 4.2

**Comment by johnsimons** [comment] 2015-03-09 22:05
@rosieks I think the issue is because that stacktrace is on a thread that nservicebus does not control.
Not sure there is much we can do here.

**Comment by rosieks** [comment] 2015-03-10 10:35
Yes, I know that there is no way to prevent that error, but it would be nice if that exception could be at least logged like in my snippet. Exception logged by .Net Runtime to event log is useless because there is no exception message.

**Comment by ramonsmits** [comment] 2015-03-10 19:17
I even have First Chance Exceptions logging enabled but *not* as level FATAL as I consider these exceptions to be handled. I log them as TRACE and dump them where I use the exception stack trace information to create a logger. This enables filtering to exclude certain first change exceptions like the timeout exceptions generated by MSMQ which occur continuously.

This has saved me enough times to easily find mysterious production issues.

So it has my approval because this is something I *always* setup if I'm responsible for monitoring/devops.

**Comment by danielmarbach** [comment] 2015-11-02 14:46
Also related to https://nservicebus.desk.com/agent/case/14537

I wouldn't consider this a bug on our side. I don't think the NServiceBus.Host should interfere with the `AppDomain.CurrentDomain.UnhandledException` event.

**Comment by SimonCropp** [comment] 2015-11-02 19:08
@danielmarbach agreed

**Comment by danielmarbach** [comment] 2015-11-02 20:25
btw. here is a repro console application which shows the behavior without NSB involvement

https://github.com/danielmarbach/NServiceBus.Support/blob/master/TransactionCompletedException/Program.cs

Exceptions in `TransactionCompleted` do not change the outcome of the transaction.

**Comment by danielmarbach** [comment] 2015-11-02 20:25
I vote for closing this one

**Comment by andreasohlund** [comment] 2015-12-21 19:28
Closing

**Closed by andreasohlund** 2015-12-21 19:28 UTC
Labels: Needs: Scheduling, Type: Bug
